version: '3.8'
services:
  react-app:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    depends_on:
      - json-server

  json-server:
    build:
      context: "./"
    ports:
      - "8000:8000"
    volumes:
      - ./tickets.json:/data/tickets.json
    command: json-server /data/tickets.json --host 0.0.0.0 --port 8000